language: python
cache: pip
python:
  - "3.6"
  - "3.7"
dist: xenial
install:
  - pip install -e '.[dev]'
script:
  - black --check --verbose motherjokes && pylint motherjokes && pytest --cov=motherjokes
after_success:
  - coveralls